### ISSUE TITLE
Move to WKWebView

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/bowser#1]
Use WKWebView instead of UIWebView. A nice overview of the capabilities of WKWebView can be found here http://nshipster.com/wkwebkit/

**Comment by ijsf** [comment]
http://stackoverflow.com/questions/25854143/wkwebview-intermittent-blank-screen-issue mentions this bug.

**Comment by ijsf** [comment]
There's a preliminary version of Bowser using WKWebView in https://github.com/ijsf/bowser/tree/wkwebview - seems to be working, though not fully tested.

**Comment by stefanalund** [comment]
Is that using the 64-bit package from Cerbero?

**Comment by ijsf** [comment]
32-bit armv7, briefly tested on iPad Mini Gen 1.

**Comment by stefanalund** [comment]
Interesting. Have you tried many different URL's? When I tried this a couple of months ago, I hit the bug linked above and some pages just rendered blank. Fixed in iOS 8.2 SDK perhaps?

**Comment by ijsf** [comment]
Haven't really tested yet. I am pretty sure that bug is eventually going to be fixed though, if it hasn't already been.

**Comment by stefanalund** [comment]
@ijsf I was thinking now would be a good time to mandate 64-bit devices only for Bowser and thus get rid of the problem of the buggy WKWebView. How far did you get with your move, does it work?

**Comment by stefanalund** [comment]
I'm working on this here https://github.com/EricssonResearch/bowser/pull/61.

**Comment by stefanalund** [comment]
#61 landed.
