### ISSUE TITLE
Ask user about using the camera and microphone

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/bowser#24]
The user should asked for permission to use the camera and microphone.

**Comment by ajbeaven** [comment]
I think this has been implemented - I got asked last time in any case.

**Comment by stefanalund** [comment]
You get asked the first time the app runs and uses WebRTC. I think this is sufficient for an app like Bowser. Re-open if you don't agree.

**Comment by stefhak** [comment]
Hm, I never got the question.
