### ISSUE TITLE
Switch between front and back cameras

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/bowser#25]
Allow the user to switch between front and back cameras

**Comment by tzafrir** [comment]
Was this documentation added? I cannot find this information anywhere

**Comment by stefanalund** [comment]
It's shown in the iOS demo app Selfie: https://github.com/EricssonResearch/openwebrtc-examples/blob/master/ios/Selfie/Selfie/SelfViewController.m

**Comment by tzafrir** [comment]
Is this exposed to Bowser's javascript API?

Google Chrome on Android supports camera selection using media constraints (ex: https://www.webrtc-experiment.com/demos/MediaStreamTrack.getSources.html)

**Comment by stefanalund** [comment]
Yes, you can use the `facingMode` attribute:
```
var mode = "user"; // or "environment"
var options = { "audio": true, "video": { "facingMode": mode } };
navigator.webkitGetUserMedia(options, function (stream) {
   ...
});
```
I have also updated the wiki: https://github.com/EricssonResearch/openwebrtc/wiki/Developing-WebRTC-web-applications-for-OpenWebRTC-and-Bowser
