### ISSUE TITLE
Add custom URL scheme

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/bowser#26]
Add a custom URL scheme so that Bowser is opened instead of Mobile Safari. 

http://stackoverflow.com/questions/8201724/how-to-register-a-custom-app-opening-url-scheme-with-xcode-4

**Comment by paericksen** [comment]
first thing to decide is what custom URL Scheme to use for Bowser.  Off the cuff, I suggest `bowser://`

**Comment by stefanalund** [comment]
Sounds good. It should then handle URLs such as:
```bowser://http://example.com```
Are you interested in helping out?

**Comment by stefanalund** [comment]
Sounds good. That would mean that Bowser should handle URLs such as:

`bowser://http://example.com`

Interested in helping out?

**Comment by paericksen** [comment]
I'd be happy to help as time permits.  I need to figure out the best way to pass the URL from the app delegate to the view controller.

**Comment by stefanalund** [comment]
There is only ever one `BowserViewController` instance so you should be able to access that from the main window owned by the app delegate.

**Comment by paericksen** [comment]
>Sounds good. That would mean that Bowser should handle URLs such as:
>bowser://http://example.com

iOS will remove the second ":" so that won't work very well.  I think the best option is to use a separate scheme for each:
* `bowser://` for `http`
* `bowsers://` for `https`


>There is only ever one BowserViewController instance so you should be able to access that from the >main window owned by the app delegate.

I think KeyValueObserving is going to be the best option for passing the launch URL to the view controller.

I should have a working example ready soon.

**Comment by stefanalund** [comment]
Thanks @paericksen, your patch looks good (just a few minor style fixes needed).

**Comment by stefanalund** [comment]
Big thanks to @paericksen, fixed in https://github.com/EricssonResearch/bowser/issues/32
