### ISSUE TITLE
Installation and configuration for work

### ISSUE THREAD

**Issue by thebestclass** [EricssonResearch/bowser#38]
I was walking around with a bad hands: I do not know develop for iOS only javascript, and I use javascript functions that need camera, audio .. there is a time I had seen the bowser but it was removed so I went back and to my surprise he is alive and free.

My intention is to just use the webview to access my website and run my normal functions and functioning as a native application (thanks to the resources that this porporsiona framework)

that's the problem, I do not know where to start! I read the wiki but feel lost, someone to guide me?

I have Mac OS Yosemite, xCode latest version

I think this will be very useful for future lays

**Comment by stefanalund** [comment]
In openwebrtc-example there is a "hybrid" app called SimpleDemo that does pretty much exactly what you are looking for. Here is tutorial to get started:

https://github.com/EricssonResearch/openwebrtc-examples/wiki/Developing-a-hybrid-iOS-app
