### ISSUE TITLE
iOS 8.1.3 : Connection to an Appear.in room never suceed

### ISSUE THREAD

**Issue by freechelmi** [EricssonResearch/bowser#47]
Hi , we tried to join a room chat on appear.in with Bower 0.5, on a local Wifi network. 

the connection started but nerver succeed.

Can this be specific to appear.in room handling ?

**Comment by stefanalund** [comment]
Appear.in blocks Bowser. I reported this to them a couple of months ago but they are still not probing for WebRTC and instead checking for certain browser. 

![image](https://cloud.githubusercontent.com/assets/190856/7783088/f4bb991c-0134-11e5-94fe-bfc6a22e7396.jpg)

**Comment by freechelmi** [comment]
Thanks for the info. that's really a pity. Do you plan some user agent switching ( I hate that as well) to overcome this ?

We plan or using bowser for our webconferencing service so we shouldn't have this problem.

**Comment by stefanalund** [comment]
It is quite simple to change the UserAgent in Bowser, but that requires rebuilding it yourself. Adding this as a customisable option in Bowser is probably not that much work. Interesting in helping out?

You would simply need to add a tableview/list with options, save the options somewhere and change the hard-coded UA to the new one.

**Comment by freechelmi** [comment]
Well I would love to help , do you think we can develop for iOS with a virtualmachine ? I won't buy a mac for that.

**Comment by stefanalund** [comment]
Sorry - that's not possible.
