### ISSUE TITLE
Version 0.5 doesn't ask for camera, doesn't work

### ISSUE THREAD

**Issue by plindseth** [EricssonResearch/bowser#48]
I'm running Bowser, as downloaded from the App Store, on an iPad Mini 2 running the latest iOS (8.3) and I'm having difficulty finding even a simple test page that uses OpenWebRTC and works. http://webrtc.github.io/samples/src/content/getusermedia/gum/ for example seems pretty simple but all I see in Bowser is a black rectangle and no prompt to allow use of the camera. Are there any test pages that will definitely work in Bowser and use the camera capabilities?

**Comment by superdump** [comment]
http://demo.openwebrtc.io/ should work.

**Comment by plindseth** [comment]
That doesn't seem to work even on a desktop. I just discovered https://www.apprtc.net/, which prompts the user to allow use of the camera and shows a (rotated for some reason) video of the user back to them, but joining a room does not work.

**Comment by superdump** [comment]
That's odd because we use http://demo.openwebrtc.io/ all the time and it works between Firefox, Chrome and OWR-based applications.

We are working toward fixing https://github.com/EricssonResearch/openwebrtc/issues/62 which apprtc triggers. We considered it an error in the standard, but the standard was not changed and so now we are fixing it.

**Comment by superdump** [comment]
The default rotation has not yet been fixed, though we do support rotation before sending now. There is some interest in implementing CVO to support rotation on the receiver-side.

**Comment by plindseth** [comment]
We cannot get that page to work on any combination of devices, even between two desktops running Chrome on the same network. We have never seen it open two video windows, even though it shows the user video from their own camera.

**Comment by superdump** [comment]
Very very odd. I do not see the same issue. Do you see any errors in the JavaScript console?

**Comment by plindseth** [comment]
On the caller side, we see a bunch of POST's with 204 content not found errors, but on the callee side, there is no output.

**Comment by superdump** [comment]
For which resources?

**Comment by mgolden-noodle** [comment]
Straight from Firebug -

URL
http://demo.openwebrtc.io:38080/ctos/1d28b3bf75a/4f95fb84527828/49f0a615?%7B%22candidate%22%3A%7B%22candidate%22%3A%22candidate%3A2%201%20UDP%201686110207%20206.217.117.226%2044481%20typ%20srflx%20raddr%2010.0.4.161%20rport%2033625%22%2C%22sdpMid%22%3A%22%22%2C%22sdpMLineIndex%22%3A0%7D%7D=

Response header

Cache-Control	no-cache, no-store
Connection	keep-alive
Content-Type	text/plain
Date	Fri, 05 Jun 2015 16:03:12 GMT
Expires	0
Pragma	no-cache

Request Header:
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	gzip, deflate
Accept-Language	en-US,en;q=0.5
Content-Length	149
Content-Type	text/plain; charset=UTF-8
DNT	1
Host	demo.openwebrtc.io:38080
Referer	http://demo.openwebrtc.io:38080/
User-Agent	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

POST Content:

{"candidate":{"candidate":"candidate:2 1 UDP 1686110207 206.217.117.226 44481 typ srflx raddr 10.0.4.161 rport 33625","sdpMid":"","sdpMLineIndex":0}}

**Comment by superdump** [comment]
I see no such problems here.
