### ISSUE TITLE
error with existing webrtc app

### ISSUE THREAD

**Issue by joergbirkhold** [EricssonResearch/bowser#50]
The app is built with easyrtc and running well in chrome and ff. but when i try to connect with bowser i get the following error:
set-remote-description: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.

**Comment by superdump** [comment]
I think it is a side effect of https://github.com/EricssonResearch/openwebrtc/issues/62 which are working to fix. There is a pull request for the fingerprint part that is up for review: https://github.com/EricssonResearch/openwebrtc/pull/427 .

I'm going to close this as the issue should be tracked in the main OpenWebRTC repository as noted above.
