### ISSUE TITLE
When enter an URL without URL-scheme "http://" or "https://" Bowser does not open the page.

### ISSUE THREAD

**Issue by Shultz78** [EricssonResearch/bowser#52]
When enter an URL without URL-scheme "http://" or "https://" Bowser does not open the page. Many other browsers can do this. 
We have a VoIP service (www.sipnet.ru) with web calls. Bowser - the only browser for iOS, with which our customers can make calls. We would like greater usability in Bowser without simple mistakes in the new version. Thank you for the good product!

**Comment by stefanalund** [comment]
Bowser is admittedly simple in what standard browser features it support. Feel free to fix this issue and submit a Pull Request if you have the possibility. Thanks.

**Comment by stefanalund** [comment]
Fixed in https://github.com/EricssonResearch/bowser/issues/62.
