### ISSUE TITLE
Crashing on iPhone 6S on iOS 9.0.2

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/bowser#60]
Crashes directly after initialisation.

**Comment by stefanalund** [comment]
Happens when injecting OWR JavaScript:

<img width="1552" alt="image" src="https://cloud.githubusercontent.com/assets/190856/10566614/d5bb9ce2-75ec-11e5-9842-87d465fa57ad.png">

**Comment by stefanalund** [comment]
Edit: Crash seems to be specific to new iPhones 6s. Does anyone know if JavaScript handling is different on the new S model compared to an iPhone 6, for example?

**Comment by jordan-green** [comment]
We're also experiencing this issue on iPhone6+ and 5. The issue is only occurring through test flight and appstore builds, it works when installed via xCode.

**Comment by Wouter0100** [comment]
We're testing it on an iPad with iOS 9.1, same behavior.

**Comment by stefanalund** [comment]
This has been solved in the latest version of OpenWebRTC, but you need to build it yourselves and replace OpenWebRTC.framework from the pod.

**Comment by jordan-green** [comment]
@stefanalund did you succesfully get anything onto the app store?

Jordan

**Comment by stefanalund** [comment]
Yes, beginning of the week. It's currently in review.
