### ISSUE TITLE
Crashes constantly

### ISSUE THREAD

**Issue by spongessuck** [EricssonResearch/bowser#67]
Immediately after installing Bowser on my iPad from the App Store, I tried to navigate to the 'Artwork' link on the Bowser homepage that the app initializes to, and the app crashes. It then crashes immediately every time I open it. Restarting the iPad didn't help. Uninstalling/re-installing Bowser didn't help.

I've attached a few crash logs.

[Bowser  11-23-15, 4-27 PM.txt](https://github.com/EricssonResearch/bowser/files/42085/Bowser.11-23-15.4-27.PM.txt)
[Bowser  11-23-15, 4-34 PM.txt](https://github.com/EricssonResearch/bowser/files/42083/Bowser.11-23-15.4-34.PM.txt)
[Bowser  11-23-15, 4-38 PM.txt](https://github.com/EricssonResearch/bowser/files/42084/Bowser.11-23-15.4-38.PM.txt)

**Comment by stefanalund** [comment]
This has been fixed in 0.6 which was recently submitted for review to the App Store. 

https://github.com/EricssonResearch/bowser/releases/tag/0.6
