### ISSUE TITLE
WebRTC not working on iOS 9.3

### ISSUE THREAD

**Issue by bcnx** [EricssonResearch/bowser#85]
Hi,

while I was trying to get WebRTC working via Chrome on an iPad, I first updated to iOS 9.3 thinking this would give the latest features and capabilities. I then learned that Chrome on iOS does not support Web RTC. I then found out that Bowser does, but after installing it and trying Jitsi-Meet (WebRTC based) , I get the error message that WebRTC is not supported on Bowser.
Could it be that something is broken with Bowser and iOS 9.3 ?

Thanks a lot,

BC

**Comment by stefanalund** [comment]
I don't think that this has anything to do with iOS 9.3. It is more likely that Jitsi does not detect Bowser as a WebRTC enabled browser (or that they use some part of WebRTC that is not supported by Bowser). I would therefore open an issue on the Jitsi Meet project instead: https://github.com/jitsi/jitsi-meet

Please re-open if you find this incorrect.

**Comment by bcnx** [comment]
Hi,

 
another WebRTC demo page did not work either, hence bringing me to the idea it was an issue with the Browser. I will chekc with the Jitsi people however,

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----
