### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by HaiderMM** [EricssonResearch/bowser#87]
Hi,

I have downloaded bowser code. when i run the application it gives the following prompt,
"No webRTC support..."

can somebody help me to resolve this issue. As far as i know that Bowser is the only browser that support webRTC on iOS.

thanks in advance.

regards,
Haider Ali Khan

**Comment by stefanalund** [comment]
Detecting WebRTC is something that the web app does. Some libraries only look for Chrome in the UserAgent header. Bowser uses this UA:

https://github.com/EricssonResearch/bowser/wiki/Developing-for-Bowser#useragent
